"use strict";

const KEYS={products:"litopsProductsV2",cart:"litopsCartV2",favorites:"litopsFavoritesV2",orders:"litopsCustomOrdersV2",subscribers:"litopsSubscribersV2"};
const FALLBACK_PRODUCTS=[
{id:"prehnite",name:"Пренит",material:"Натуральный пренит · нержавеющая сталь",description:"Светло-зелёный минерал с прозрачной глубиной.",price:5490,image:"assets/products/prehnite.webp",categories:["light","rare","steel","gift"],badge:"Выбор мастера",stock:8,featured:true,color:"green",hardware:"steel",clasp:true,colorLabel:"Зелёный",hardwareLabel:"Высококачественная нержавеющая сталь",braceletCountry:"Россия",stoneCountry:"Южная Африка",set:["бирка","мешочек для хранения","подарочная упаковка","браслет"]},
{id:"tourmaline",name:"Турмалин",material:"Натуральный турмалин · нержавеющая сталь",description:"Яркий мультиколор с розовыми, зелёными и золотистыми оттенками.",price:4890,image:"assets/products/tourmaline.webp",categories:["color","rare","steel","gift"],badge:"Новинка",stock:6,featured:true,color:"multi",hardware:"steel",clasp:true,colorLabel:"Мультиколор",hardwareLabel:"Высококачественная нержавеющая сталь",braceletCountry:"Россия",stoneCountry:"Бразилия",set:["бирка","мешочек для хранения","браслет"]},
{id:"rutilated-quartz",name:"Кварц рутиловый",material:"Натуральный кварц · нержавеющая сталь",description:"Прозрачный кварц с золотистыми включениями рутила.",price:4690,image:"assets/products/rutilated-quartz.webp",categories:["light","rare","steel","gift"],badge:"Редкий камень",stock:5,featured:true,color:"gold",hardware:"steel",clasp:false,colorLabel:"Золотистый",hardwareLabel:"Высококачественная нержавеющая сталь",braceletCountry:"Россия",stoneCountry:"Бразилия",set:["бирка","мешочек для хранения","подарочная упаковка","браслет"]},
{id:"larimar",name:"Ларимар",material:"Натуральный ларимар · нержавеющая сталь",description:"Голубой минерал с облачным природным рисунком.",price:6290,image:"assets/products/larimar.webp",categories:["light","color","rare","steel","gift"],badge:"Хит",stock:4,featured:true,color:"blue",hardware:"steel",clasp:true,colorLabel:"Голубой",hardwareLabel:"Высококачественная нержавеющая сталь",braceletCountry:"Россия",stoneCountry:"Доминиканская Республика",set:["бирка","мешочек для хранения","браслет"]},
{id:"labradorite",name:"Лабрадор",material:"Натуральный лабрадорит · нержавеющая сталь",description:"Серо-синий камень с глубокими переливами.",price:6790,image:"assets/products/labradorite.webp",categories:["color","rare","steel","gift","dark"],badge:"Бестселлер",stock:7,featured:true,color:"dark",hardware:"steel",clasp:true,colorLabel:"Тёмный с переливом",hardwareLabel:"Высококачественная нержавеющая сталь",braceletCountry:"Россия",stoneCountry:"Мадагаскар",set:["бирка","мешочек для хранения","подарочная упаковка","браслет"]},
{id:"charoite",name:"Чароит",material:"Натуральный чароит · нержавеющая сталь",description:"Фиолетовый минерал с выразительной волокнистой фактурой.",price:5990,image:"assets/products/charoite.webp",categories:["color","rare","steel","gift"],badge:"Новинка",stock:5,featured:true,color:"purple",hardware:"steel",clasp:false,colorLabel:"Фиолетовый",hardwareLabel:"Высококачественная нержавеющая сталь",braceletCountry:"Россия",stoneCountry:"Россия",set:["бирка","мешочек для хранения","браслет"]}
];
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))||structuredClone(f)}catch{return structuredClone(f)}};
const write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch(e){console.warn(e)}};
const price=v=>new Intl.NumberFormat("ru-RU").format(+v||0)+" ₽";
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const $=id=>document.getElementById(id);
const state={products:read(KEYS.products,FALLBACK_PRODUCTS),cart:read(KEYS.cart,{}),favorites:new Set(read(KEYS.favorites,[])),quick:"all",sort:"featured",advanced:null,draft:null};
let toastTimer;
function icons(){window.lucide?.createIcons({attrs:{"stroke-width":1.8}})}
function normalize(){state.products=(Array.isArray(state.products)&&state.products.length?state.products:FALLBACK_PRODUCTS).map((p,i)=>({...FALLBACK_PRODUCTS[i%FALLBACK_PRODUCTS.length],...p,categories:Array.isArray(p.categories)?p.categories:FALLBACK_PRODUCTS[i%FALLBACK_PRODUCTS.length].categories,set:Array.isArray(p.set)?p.set:FALLBACK_PRODUCTS[i%FALLBACK_PRODUCTS.length].set,material:(p.material||FALLBACK_PRODUCTS[i%FALLBACK_PRODUCTS.length].material).replace(/серебро\s*925|серебро/gi,"нержавеющая сталь")}));write(KEYS.products,state.products);const b=bounds();state.advanced={minPrice:b.min,maxPrice:b.max,colors:new Set(),hardware:"all",clasp:"all"}}
function bounds(){const ps=state.products.map(p=>+p.price||0);return{min:Math.min(...ps),max:Math.max(...ps)}}
function visible(filter=state.advanced){let a=state.products.filter(p=>(state.quick==="all"||p.categories.includes(state.quick))&&p.price>=filter.minPrice&&p.price<=filter.maxPrice&&(!filter.colors.size||filter.colors.has(p.color))&&(filter.hardware==="all"||p.hardware===filter.hardware)&&(filter.clasp==="all"||(filter.clasp==="yes"?p.clasp:!p.clasp)));a.sort((x,y)=>state.sort==="price-asc"?x.price-y.price:state.sort==="price-desc"?y.price-x.price:state.sort==="name"?x.name.localeCompare(y.name,"ru"):Number(y.featured)-Number(x.featured)||x.name.localeCompare(y.name,"ru"));return a}
function card(p){return `<article class="product-card" data-product-id="${esc(p.id)}"><div class="product-card__media open-product" tabindex="0"><span class="tiny-badge product-card__badge">${esc(p.badge)}</span><button class="product-card__favorite ${state.favorites.has(p.id)?"is-active":""}" data-action="favorite" aria-label="В избранное"><i data-lucide="heart"></i></button><img src="${esc(p.image)}" alt="${esc(p.name)}"></div><div class="product-card__content"><p class="product-card__meta">${esc(p.material)}</p><h3>${esc(p.name)}</h3><p class="product-card__description">${esc(p.description)}</p><div class="product-card__footer"><div><strong class="product-card__price">${price(p.price)}</strong><p class="product-card__stock">${p.stock?`В наличии: ${p.stock}`:"Под заказ"}</p></div><div class="product-card__actions"><button class="open-product">Подробнее</button><button class="add-to-cart" data-action="cart"><i data-lucide="shopping-bag"></i></button></div></div></div></article>`}
function renderProducts(){const a=visible();$("productGrid").innerHTML=a.map(card).join("");$("emptyState").hidden=!!a.length;renderSpotlight(a[0]||state.products[0]);icons()}
function renderSpotlight(p){if(!p)return;$("spotlightCard").innerHTML=`<img src="${esc(p.image)}" alt="${esc(p.name)}"><div class="spotlight-product__info"><span class="tiny-badge">${esc(p.badge)}</span><h3>${esc(p.name)}</h3><p>${esc(p.description)}</p><div class="spotlight-product__price"><strong>${price(p.price)}</strong><button class="main-button main-button--gold" data-product-open="${esc(p.id)}">Подробнее</button></div></div>`}
function summary(){let count=0,total=0;for(const[id,q]of Object.entries(state.cart)){const p=state.products.find(x=>x.id===id);if(p&&q>0){count+=q;total+=p.price*q}}$("cartCount").textContent=count;$("cartSummary").textContent=price(total);$("cartTotal").textContent=price(total);$("favoriteCount").textContent=state.favorites.size}
function renderCart(){const a=Object.entries(state.cart).filter(([id,q])=>q>0&&state.products.some(p=>p.id===id));$("cartItems").innerHTML=a.length?a.map(([id,q])=>{const p=state.products.find(x=>x.id===id);return `<article class="drawer-item" data-product-id="${id}"><img src="${p.image}" alt="${esc(p.name)}"><div><h3>${esc(p.name)}</h3><p>${esc(p.material)}</p><strong>${price(p.price*q)}</strong></div><div class="drawer-item__controls"><button data-cart-action="remove"><i data-lucide="trash-2"></i></button><div class="quantity-control"><button data-cart-action="decrease">−</button><span>${q}</span><button data-cart-action="increase">+</button></div></div></article>`}).join(""):`<div class="drawer-empty"><i data-lucide="shopping-bag"></i><p>В корзине пока нет изделий.</p></div>`;summary();icons()}
function renderFavorites(){const a=state.products.filter(p=>state.favorites.has(p.id));$("favoriteItems").innerHTML=a.length?a.map(p=>`<article class="drawer-item" data-product-id="${p.id}"><img src="${p.image}" alt="${esc(p.name)}"><div><h3>${esc(p.name)}</h3><p>${esc(p.material)}</p><strong>${price(p.price)}</strong></div><div class="drawer-item__controls"><button data-favorite-action="remove"><i data-lucide="heart-off"></i></button><button data-favorite-action="cart"><i data-lucide="shopping-bag"></i></button></div></div></article>`).join(""):`<div class="drawer-empty"><i data-lucide="heart"></i><p>В избранном пока ничего нет.</p></div>`;summary();icons()}
function addCart(id){state.cart[id]=(state.cart[id]||0)+1;write(KEYS.cart,state.cart);renderCart();toast("Товар добавлен в корзину")}
function favorite(id){state.favorites.has(id)?state.favorites.delete(id):state.favorites.add(id);write(KEYS.favorites,[...state.favorites]);renderProducts();renderFavorites();summary()}
function drawer(el){document.querySelectorAll(".side-drawer").forEach(x=>x.classList.remove("is-open"));el.classList.add("is-open");$("drawerBackdrop").classList.add("is-visible");document.body.classList.add("is-locked")}
function closeDrawers(){document.querySelectorAll(".side-drawer").forEach(x=>x.classList.remove("is-open"));$("drawerBackdrop").classList.remove("is-visible");document.body.classList.remove("is-locked")}
function openProduct(id){const p=state.products.find(x=>x.id===id);if(!p)return;$("dialogImage").src=p.image;$("dialogName").textContent=p.name;$("dialogMaterial").textContent=p.material;$("dialogDescription").textContent=p.description;$("dialogPrice").textContent=price(p.price);$("dialogAddToCart").dataset.productId=p.id;$("dialogFacts").innerHTML=[p.badge,p.colorLabel,p.clasp?"С замком":"Без замка"].map(x=>`<span>${esc(x)}</span>`).join("");$("dialogSpecs").innerHTML=[["Материал фурнитуры",p.hardwareLabel],["Страна изготовления",p.braceletCountry],["Происхождение камня",p.stoneCountry],["Комплектация",p.set.join(", ")]].map(([a,b])=>`<div><dt>${esc(a)}</dt><dd>${esc(b)}</dd></div>`).join("");$("productDialog").showModal();icons()}
function toast(t){clearTimeout(toastTimer);$("toast").textContent=t;$("toast").classList.add("is-visible");toastTimer=setTimeout(()=>$("toast").classList.remove("is-visible"),2200)}
function openSearch(){$("searchPanel").classList.add("is-open");document.body.classList.add("is-locked");search("");setTimeout(()=>$('searchInput').focus(),50)}
function closeSearch(){$("searchPanel").classList.remove("is-open");document.body.classList.remove("is-locked")}
function search(q){q=q.trim().toLowerCase();const a=state.products.filter(p=>!q||`${p.name} ${p.material} ${p.description}`.toLowerCase().includes(q));$("searchResults").innerHTML=a.map(p=>`<article class="search-result" data-product-id="${p.id}"><img src="${p.image}" alt="${esc(p.name)}"><div><h3>${esc(p.name)}</h3><p>${esc(p.material)}</p><strong>${price(p.price)}</strong></div></article>`).join("")||"<p>Ничего не найдено.</p>"}
function filterOpen(){state.draft={...state.advanced,colors:new Set(state.advanced.colors)};syncFilter();$("filterDialog").showModal();icons()}
function syncFilter(){const b=bounds(),f=state.draft;["priceMinRange","priceMaxRange"].forEach(id=>{const e=$(id);e.min=b.min;e.max=b.max});$("priceMinRange").value=f.minPrice;$("priceMaxRange").value=f.maxPrice;$("priceMinInput").value=f.minPrice;$("priceMaxInput").value=f.maxPrice;$("averagePriceLabel").textContent=price(Math.round(state.products.reduce((s,p)=>s+p.price,0)/state.products.length));$("selectedRangeLabel").textContent=`${price(f.minPrice)} — ${price(f.maxPrice)}`;const span=Math.max(b.max-b.min,1),l=(f.minPrice-b.min)/span*100,r=100-(f.maxPrice-b.min)/span*100;$("rangeFill").style.left=l+"%";$("rangeFill").style.right=r+"%";document.querySelectorAll('#colorFilterGroup input').forEach(e=>e.checked=f.colors.has(e.value));document.querySelectorAll('input[name="hardware"]').forEach(e=>e.checked=e.value===f.hardware);document.querySelectorAll('input[name="clasp"]').forEach(e=>e.checked=e.value===f.clasp);renderPeaks();$("filterResultCount").textContent=visible(f).length}
function renderPeaks(){const f=state.draft,b=bounds(),n=24,span=Math.max(b.max-b.min,1);$("pricePeaks").innerHTML=Array.from({length:n},(_,i)=>{const x=b.min+span*i/(n-1),center=(b.min+b.max)/2,height=22+58*(1-Math.abs(x-center)/(span/2))*.75+Math.sin(i*.9)*8;return `<span class="price-peak ${x>=f.minPrice&&x<=f.maxPrice?"is-active":"is-muted"}" style="height:${Math.max(16,height)}px"></span>`}).join("")}
function setPrice(type,v){const b=bounds(),n=Math.max(b.min,Math.min(b.max,+v||b.min));type==="min"?state.draft.minPrice=Math.min(n,state.draft.maxPrice):state.draft.maxPrice=Math.max(n,state.draft.minPrice);syncFilter()}
function activeBadge(){const b=bounds();let n=state.advanced.colors.size+(state.advanced.hardware!=="all")+(state.advanced.clasp!=="all")+(state.advanced.minPrice!==b.min||state.advanced.maxPrice!==b.max);$("activeFilterCount").hidden=!n;$("activeFilterCount").textContent=n}
function reveal(){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add("is-visible");io.unobserve(e.target)}}),{threshold:.1});document.querySelectorAll(".reveal").forEach(e=>io.observe(e))}
function init(){normalize();$("heroImage").src="assets/products/labradorite.webp";renderProducts();renderCart();renderFavorites();summary();activeBadge();icons();reveal();
window.addEventListener("scroll",()=>$("siteHeader").classList.toggle("is-scrolled",scrollY>20),{passive:true});
$("menuButton").onclick=()=>{const o=$("mainNav").classList.toggle("is-open");$("menuButton").setAttribute("aria-expanded",o)};
$("mainNav").onclick=e=>{if(e.target.closest("a"))$("mainNav").classList.remove("is-open")};
$("searchButton").onclick=openSearch;$("searchClose").onclick=closeSearch;$("searchInput").oninput=e=>search(e.target.value);$("searchResults").onclick=e=>{const r=e.target.closest(".search-result");if(r){closeSearch();openProduct(r.dataset.productId)}};
$("categoryBar").onclick=e=>{const b=e.target.closest("[data-filter]");if(!b)return;state.quick=b.dataset.filter;document.querySelectorAll("[data-filter]").forEach(x=>x.classList.toggle("is-active",x===b));renderProducts()};
$("sortSelect").onchange=e=>{state.sort=e.target.value;renderProducts()};
$("productGrid").onclick=e=>{const c=e.target.closest(".product-card");if(!c)return;const id=c.dataset.productId;if(e.target.closest('[data-action="favorite"]'))favorite(id);else if(e.target.closest('[data-action="cart"]'))addCart(id);else if(e.target.closest(".open-product"))openProduct(id)};
$("spotlightCard").onclick=e=>{const b=e.target.closest("[data-product-open]");if(b)openProduct(b.dataset.productOpen)};$("openFeaturedDialog").onclick=()=>{const p=visible()[0]||state.products[0];if(p)openProduct(p.id)};
$("cartButton").onclick=()=>{renderCart();drawer($("cartDrawer"))};$("favoritesButton").onclick=()=>{renderFavorites();drawer($("favoritesDrawer"))};$("drawerBackdrop").onclick=closeDrawers;document.querySelectorAll("[data-close-drawer]").forEach(b=>b.onclick=closeDrawers);
$("cartItems").onclick=e=>{const a=e.target.closest("[data-cart-action]"),item=e.target.closest(".drawer-item");if(!a||!item)return;const id=item.dataset.productId;a.dataset.cartAction==="increase"?state.cart[id]++:a.dataset.cartAction==="decrease"?state.cart[id]--:delete state.cart[id];if(state.cart[id]<=0)delete state.cart[id];write(KEYS.cart,state.cart);renderCart()};
$("favoriteItems").onclick=e=>{const a=e.target.closest("[data-favorite-action]"),item=e.target.closest(".drawer-item");if(!a||!item)return;a.dataset.favoriteAction==="remove"?favorite(item.dataset.productId):addCart(item.dataset.productId)};
$("dialogClose").onclick=()=>$("productDialog").close();$("dialogAddToCart").onclick=e=>addCart(e.currentTarget.dataset.productId);$("productDialog").onclick=e=>{if(e.target===$("productDialog"))$("productDialog").close()};
$("openOrderButton").onclick=()=>$("orderDialog").showModal();$("orderDialogClose").onclick=()=>$("orderDialog").close();$("customOrderForm").onsubmit=e=>{e.preventDefault();const a=read(KEYS.orders,[]);a.unshift({id:"request-"+Date.now(),createdAt:new Date().toISOString(),status:"Новая",...Object.fromEntries(new FormData(e.currentTarget))});write(KEYS.orders,a);$("orderFormStatus").textContent="Заявка сохранена.";e.currentTarget.reset();toast("Заявка сохранена")};
$("newsletterForm").onsubmit=e=>{e.preventDefault();const mail=new FormData(e.currentTarget).get("email").trim();const a=read(KEYS.subscribers,[]);if(mail&&!a.includes(mail))a.push(mail);write(KEYS.subscribers,a);$("newsletterMessage").textContent="Спасибо! Адрес сохранён.";e.currentTarget.reset()};
$("filterOpenButton").onclick=filterOpen;$("filterCloseButton").onclick=()=>$("filterDialog").close();$("filterResetButton").onclick=()=>{const b=bounds();state.draft={minPrice:b.min,maxPrice:b.max,colors:new Set(),hardware:"all",clasp:"all"};syncFilter()};$("filterForm").onsubmit=e=>{e.preventDefault();state.advanced={...state.draft,colors:new Set(state.draft.colors)};activeBadge();renderProducts();$("filterDialog").close()};
$("priceMinRange").oninput=e=>setPrice("min",e.target.value);$("priceMaxRange").oninput=e=>setPrice("max",e.target.value);$("priceMinInput").oninput=e=>setPrice("min",e.target.value);$("priceMaxInput").oninput=e=>setPrice("max",e.target.value);document.querySelectorAll('#colorFilterGroup input').forEach(x=>x.onchange=()=>{x.checked?state.draft.colors.add(x.value):state.draft.colors.delete(x.value);syncFilter()});document.querySelectorAll('input[name="hardware"]').forEach(x=>x.onchange=()=>{state.draft.hardware=x.value;syncFilter()});document.querySelectorAll('input[name="clasp"]').forEach(x=>x.onchange=()=>{state.draft.clasp=x.value;syncFilter()});
}
document.addEventListener("DOMContentLoaded",init);
